Task.create(name: "Cook", description: "do something", complete: false)
Task.create(name: "Clean", description: "do something", complete: false)
Task.create(name: "Bake", description: "do something", complete: false)
Task.create(name: "Exercise", description: "do something", complete: false)
Task.create(name: "Work", description: "do something", complete: true)